### ISSUE TITLE
IGFD_API macro redefinition warning

### ISSUE THREAD

**Issue by njk42** [aiekick/ImGuiFileDialog#175]
I'm using ImGuiFileDialog version 0.6.7 in a cmake project on Windows 10 via Visual Studio 2022; consuming statically per recommendation in the header on line 1387.

I get a compiler warning that:
Warning	    C4005 'IGFD_API': macro redefinition      <path>\ImGuiFileDialog.h      2296	

IGFD_API is #defined as "__declspec(dllexport)" on line 2296, but also #defined as "" on line 1393.

Seems pretty benign, but am I doing something wrong which should be done differently in order to avoid this warning?  E.g. should I be explicitly defining IMGUIFILEDIALOG_NO_EXPORT in my client code?

**Comment by aiekick** [comment]
Hello,

No you dont need to do anything.

Its my fault.

I will remove the explicit declaration of __declspec(dllexport). so the block of lines 2292 to 2304.
Like for the cpp part. its the responsibilty of the user to define what he want in the IGFD_API

this warning is appearing now since from a PR form 2 weeks ago we have renamed the cpp API Code.

and sa i not using the C Api, i didnt noticed this warnings

**Comment by njk42** [comment]
Many thanks @aiekick!  Your solution for file dialogs in DearImGui is much appreciated.

**Comment by aiekick** [comment]
fixed.
