### ISSUE TITLE
Question: Disable OK if file isn't selected?

### ISSUE THREAD

**Issue by chaoticbob** [aiekick/ImGuiFileDialog#36]
Hi - is there a way to disable the OK button (or make it not clickable) if a file hasn't been selected? Thanks

**Comment by aiekick** [comment]
hello,

no, but i can deactivate the ok button when the file field is empty.
because when you select a file or a directory the file field is not empty.

so it make sense in any case (open and save behaviors) to disable ok button when empty.
so you need to not define default filename

it can wrok for you ?

**Comment by chaoticbob** [comment]
Sorry about the late reply. If you still plan on doing this it sounds great and definitely seems useful to me.

**Comment by aiekick** [comment]
its already comitted :)
