### ISSUE TITLE
Release  has an empty  ImGuiFileDialog directory

### ISSUE THREAD

**Issue by farzonl** [aiekick/ImGuiFileDialog#50]
**Describe the bug**
If you download:
https://github.com/aiekick/ImGuiFileDialog/archive/v0.5.5.zip

The submodule is making the `ImGuiFileDialog`  directory empty the only way to get everything is by git cloning the repo and running 
```
git submodule init
git submodule update
```
The result is that taking a dependency on the release isn't possible.

I recommend switching to a mono repo, but any solution that fixes the ImGuiFileDialog-0.5.5.zip and subsequent releases would be awesome.

**Comment by aiekick** [comment]
thanks for the feedback
indeed. i think i will put only the lib in master and keep sample app in other branch

**Comment by aiekick** [comment]
i tried but in fact i will not doing that. due to actions system for github.
the workflow files for launch action (here for build the lib) are from default branch only.

btw for your issue, its my fault, when i draft a new release, i can select the branch, and by the past i only selected master, so if i select instead Lib_Only, he will be fine. will do that for next release :)
