### ISSUE TITLE
Allow double click  and intro to select a file.

### ISSUE THREAD

**Issue by phcerdan** [aiekick/ImGuiFileDialog#56]
I can double-click to navigate into a folder, or use  ~~intro~~ enter key when `#def USE_EXPLORATION_BY_KEYS`, however, I cannot double-click or press enter to select the file.

Would it be possible to allow double-click/enter key to "press OK button" if the selected item is a file?

**Comment by aiekick** [comment]
what do you mean by "intro" key ?

**Comment by phcerdan** [comment]
I meant the "enter" key, sorry, as defined here:

```cpp
// Enter key for open directory
#define IGFD_KEY_ENTER GLFW_KEY_ENTER
```

**Comment by aiekick** [comment]
ok yes => to do

**Comment by davidsanda** [comment]
I just came here to add this very suggestion. Please add double-click to select the file. Just a minor thing. Your work rocks!
Thank you for your effort.

**Comment by aiekick** [comment]
so like phcardan ? this mean doucle click => file selection + ok button of the dialog ?

**Comment by davidsanda** [comment]
Exactly.

**Comment by aiekick** [comment]
just sorry for the moment im fully busy. i guess i could fix/add this weekend

**Comment by aiekick** [comment]
i just pushed a partial solution.
you can double clik on a file for directly select and close dialog but :
- the confirm to overwrite dialog can be shown, and there is no way for the moment to use it without mouse, except with the kbd navigation of imgui
- for the directory chooser, i have no idea how to do for select and close, because the double click is sued for open the selected directory

if you have any idea, pelase share.

to note, the enter key is always buggy for the moment => to fix.
because when you hit enter he not take into account the current selected directory but get the first dir of the list..
