### ISSUE TITLE
Support for wide-chars as casual calls to i.e. GetDirectory functions are LPWSTR 

### ISSUE THREAD

**Issue by MaKiPL** [aiekick/ImGuiFileDialog#6]
**Describe the bug**
Currently the code tends to support only ANSI strings- however calls to functions like GetFullPathName or GetLogicalDriveStrings are extended to GetLogicalDriveStringsW, not GetLogicalDriveStringsA- therefore ImGuiFileDialog will crash as it won't expect one-byte char but two-bytes char if strings will be cased to LPCWSTR or LPWSTR

**To Reproduce**
-/-

**Expected behavior**
Change all std::string to std::wstring and char to WCHAR

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio 2019 with C++17

**Comment by aiekick** [comment]
ok, im not very familiar with wide chars.
its for unicode support ?

can you propose a PR ?

**Comment by aiekick** [comment]
if i change all std::string to std::wstring and char to WCHAR i break ImGui, who is not supproting wide char for the moment.
it will be difficult to support both modes. but i can use only GetLogicalDriveStringsA, CreateDirectoryA, and other func directly for avoid unicode crash

**Comment by sonoro1234** [comment]
Wide char version of windows functions should be used, then wide chars are converted to utf-8 so that imgui could use them. When you go from imgui to wide chat filesystem functions you need the opposite conversion.
Basically you need two functions: from WideChar2UTF and UTF2WideChar,
This are the ones I made for LuaJIT: https://github.com/sonoro1234/luafilesystem/blob/unicode/lfs_ffi.lua#L190

**Comment by aiekick** [comment]
if i do in code
#define std::string std::wtring
#define char wchar_t
with corret include file as well
when we want wchar ? its ok ?

because i found many issue with wchar in the imgui doc about perf. not sure about the problem and the solution you propose, since i have no more information

the best way is, you propose a PR i think

**Comment by aiekick** [comment]
hello there,

i have finally created an implementation with std::filesystem (c++17) of the new ImGuiFileDialog

you just need to use this define in the config file

#define USE_STD_FILESYSTEM

you can test that in the branch : https://github.com/aiekick/ImGuiFileDialog/tree/Lib_Only_Std__FileSystem_WIP

as i know the unicode is fully supported now, ( just fixed a bug in the path composer)
