### ISSUE TITLE
Not an Issue. Just a thank you!

### ISSUE THREAD

**Issue by time-killer-games** [aiekick/ImGuiFileDialog#71]
This may be closed when you see it. I just wanted to say thanks for making this, you're a life saver. I orignally wrote a library which uses native dialogs and is cross-platform but maintenance on macOS became a bit annoying, so this makes for a nice fallback solution that won't face constant breakage every new major OS version, like I would I've had to deal with using NSOpenPanel and NSSavePanel.

I would like to contribute an example for using this with the SDL2Renderer, as an extra means of saying thank you.

The example will look similar to this:

![IPRQpmz](https://user-images.githubusercontent.com/4379204/146608203-9cfd095e-5c31-475c-a511-91a5a28ddd86.png)

I'll submit a pr shortly. Thanks again!
Samuel

**Comment by aiekick** [comment]
thanks :)

its a pleasure, to see that kind of post :)

**Comment by time-killer-games** [comment]
@aiekick hey, I'm ready to make the pr, was wondering if where the files should go in your repository before getting started:

https://github.com/time-killer-games/ImGuiFileDialogSDL2RendererExample

**Comment by aiekick** [comment]
sorry, i not understood you would like to post a pr for ImGuiFileDialog with SDL. 
its not necessary.

i can just a add a config in the CMakeList.txt of the current app in master with the sdl as a submodule if needed

but its not necessary since each guys can easily use ImGuiFileDialog with their current imgui configuration. 

the purpose of the app was just to show how to use it. this is eactly the same code for each backend.
and im working with glfw, and i need to maintain this app for each modification, so its better if you let me write the app.

sorry, but thanks for your understanding and your consideration
